on:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/386
          - linux/arm64
          - linux/arm/v6
          - linux/arm/v7
          - linux/riscv64
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.4.0
        with:
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/claytonsingh/ubuntu-golang:latest
