on:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { platform: "linux/amd64",   goarch: "amd64"   }
          - { platform: "linux/386",     goarch: "386"     }
          - { platform: "linux/arm64",   goarch: "arm64"   }
          - { platform: "linux/arm/v7",  goarch: "armv7l"  }
          - { platform: "linux/arm/v5",  goarch: "armv6l"  }
          - { platform: "linux/riscv64", goarch: "riscv64" }
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.4.0
        with:
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/claytonsingh/ubuntu-golang:latest
          build-args: |
            GOARCH=${{ matrix.goarch }}
